<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<section data-cy="todo">
    <h2><?= $block->escapeHtml(__('Tasks for today')) ?></h2>
    <div data-bind="scope: 'todoList'"><!-- ko template: getTemplate() --><!-- /ko --></div>
</section>
<script type="text/x-magento-init">
{"*":{"Magento_Ui/js/core/app":{"components":{"todoList":{"component":"Vitalii_TodoList/js/list"}}}}}
</script>
