upstream fastcgi_backend {
    server unix:/sock/phpfpm.sock;
}
server {
    listen __CYPRESS_VIEW_PORT__ ssl;
    absolute_redirect off;
    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;
    server_name _;
    resolver 127.0.0.11 valid=10s;
    location = / {
        return 302 /vnc.html?autoconnect=1&resize=scale&view_only=1&reconnect=1;
    }
    location / {
        set $desktop http://runner:6080;
        proxy_pass $desktop;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_buffering off;
        add_header Cache-Control no-cache;
    }
}
server {
    listen __APPLICATION_PORT__;
    listen __APPLICATION_HTTPS_PORT__ ssl;
    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;
    keepalive_requests 100000;
    server_name _;
    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 8 128k;
    include /var/www/html/nginx.conf.sample;
}
